### ISSUE TITLE
GDML Export

### ISSUE THREAD

**Issue by rpezzi** [KeithSloan/FreeCAD_Python_GDML#1]
GDML Export on FreeCAD would be nice. Any plans for that?

**Comment by KeithSloan** [comment]
See branch gdml on https://github.com/KeithSloan/FreeCAD_sf_master its a port of the work done by  Emmanuel Delage see http://cad-gdml.in2p3.fr/ It now works with the latest version of FreeCAD, but on testing I hit a problem where it did not handle opening a second file properly i.e. opening a file sometimes opens the wrong file. I stopped work on it until I can work out how to debug.

**Comment by rpezzi** [comment]
Thanks. This is great. I have compiled your gdml fork and successfully exported a simple project to a GDML file. However I noticed that boolean operations are not yet implemented (at least not subtraction). I will keep an eye on it and try to help.
