### ISSUE TITLE
Use default world material vacuum instead of air

### ISSUE THREAD

**Issue by wdconinc** [KeithSloan/FreeCAD_Python_GDML#2]
Instead of the current default of G4_Air (which relies on a whole bunch of isotopes, elements, etc), it may make more sense to use G4_Galactic as the default material for the world, e.g. defined on L1807 at http://www.apc.univ-paris7.fr/~franco/g4doxy/html/G4NistMaterialBuilder_8cc-source.html. Equivalent block in gdml is:
```
    <material Z="1" name="G4_Galactic" state="gas">
      <T unit="K" value="2.73"/>
      <P unit="pascal" value="3e-18"/>
      <D unit="g/cm3" value="1e-25"/>
      <atom unit="g/mole" value="1.01"/>
    </material>
```
Rationale: it reduces the amount of non-essential content in the output gdml file.

**Comment by KeithSloan** [comment]
Should be fixed in latest workbench branch.
Will think about reducing material to minimum in the future
