### ISSUE TITLE
Process internal XML entities before processing DOM on import

### ISSUE THREAD

**Issue by wdconinc** [KeithSloan/FreeCAD_Python_GDML#3]
Currently the importing of gdml files with XML entities (supported by GDML in Geant4 per user guide) results in throwing an error due to failure to parse the entity. Here I'm just using a single value entity &length;. Error produced upon import is:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/freecad-daily/Mod/GDML/importGDML.py", line 60, in insert
    processGDML(filename)
  File "/usr/lib/freecad-daily/Mod/GDML/importGDML.py", line 223, in processGDML
    parseVolume(root,ref,0,0,0)
<type 'exceptions.TypeError'>: parseVolume() takes exactly 3 arguments (5 given)
```
GDML input file:
https://gist.github.com/wdconinc/5608821687745aa701391229d5b6504c

**Comment by wdconinc** [comment]
Upgrading from the stdlib xml parser to the lxml parser appears the easiest fix here. It adds a dependency.
```
diff --git a/Mod/importGDML.py b/Mod/importGDML.py
index fab474a..992e34e 100644
--- a/Mod/importGDML.py
+++ b/Mod/importGDML.py
@@ -237,8 +237,10 @@ def processGDML(filename):
     FreeCAD.Console.PrintMessage('Import GDML file : '+filename+'\n')
     if printverbose: print ('ImportGDML Version 0.1')
 
-    import xml.etree.ElementTree as ET
-    tree = ET.parse(filename)
+    import lxml.etree as ET
+    parser = ET.XMLParser(load_dtd = True, resolve_entities = True)
+
+    tree = ET.parse(filename, parser = parser)
     root = tree.getroot()
 
     for setup in root.find('setup'):
```

**Comment by KeithSloan** [comment]
Not sure how easy this will be to deal with in Python.

Have updated sister development https://github.com/KeithSloan/FreeCAD_Geant4 to include the same workbench in all but name and same export. It uses the Geant4 python library to parse the GDML file so hopefully will handle this and other situations. It does have the disadvantage of needing to install Geant4 from source. It is also VERY slow and you have to click on retry when FreeCAD prompts about not responding. You need to take care if both FreeCAD extensions are installed as they will both try to say they handle a GDML file and only one will. On my system I have one installed on freecad and the other in freecad-daily

**Comment by KeithSloan** [comment]
Tried with sister development and it handles entity1.gdml okay.

Be careful if you install both applications in the same version of FreeCAD as only one will get to process GDML files. I have one Application installed in freecad and the other in freecad-daily

**Comment by KeithSloan** [comment]
Should be fixed in latest workbench branch - so closing.

Please reopen if you find problems.
