### ISSUE TITLE
OT: Macro_ObjectInfo

### ISSUE THREAD

**Issue by lewie** [KeithSloan/FreeCAD_Python_GDML#33]
Hey Keith,
I had installed your WorkBench ObjectInfo (https://www.freecadweb.org/wiki/Macro_ObjectInfo) in my FreeCad for many years. 

But after a reinstall I have lost now. The download-link in documentation is not working yet:
http://keithsloan.dynu.com/Keith&Jenny/FreeCAD/Info/Info.zip

Can you please send me the file info.zip in any way?

Thank you very much 
lewie

**Comment by KeithSloan** [comment]
Crumbs I will have to have a dig around to see if I can find a copy.

**Comment by KeithSloan** [comment]
Okay untested please check https://github.com/KeithSloan/FreeCAD_Info.

I seem to have several old versions lying around.

Let me know how you get on.

**Comment by KeithSloan** [comment]
Hopefully closed see [https://github.com/KeithSloan/FreeCAD_Info](url)
