### ISSUE TITLE
lxml pb under FreeCAD_0.19-20310

### ISSUE THREAD

**Issue by lambdam94** [KeithSloan/FreeCAD_Python_GDML#35]
Hello,

I tried to used  FreeCAD_Python_GDML. So I have donwloaded the last FreeCAD version available  0.19

But with FreeCAD_Python_GDML, a error occured :
 File "/home/.../.FreeCAD/Mod/GDML/freecad/gdml/importGDML.py", line 977, in processGDML
    from lxml import etree
<class 'ModuleNotFoundError'>: No module named 'lxml'

could you help?
Thanks!
Regards

**Comment by KeithSloan** [comment]
It requires lxml

See installation instructions

sudo  apt-get install python3-lxml

You would be better off installing [https://github.com/KeithSloan/GDML](url)
It is a new format version of the GDML workbench and has a number of fixes that are not in this Repro.

**Comment by lambdam94** [comment]
Hello Keith

thanks for your answer,

I have done
sudo apt-get install python3-lxml  (now under python3 "import lxml" is ok)
and
sudo apt-get install python-lxml (now under python "import lxml" is ok)
and downloaded your new code.

But I still have the same pb

ile ".FreeCAD/Mod/GDML/freecad/gdml/importGDML.py", line 977, in processGDML

from lxml import etree

<class 'ModuleNotFoundError'>: No module named 'lxml'

It seems that Freecad has his own python environment.
I tried with FreeCAD_0.19-20310-Linux-Conda_glibc2.12-x86_64.AppImag
Do you think I should try with another FreeCAD version?

Regards
Dam



Le mar. 31 mars 2020 à 20:31, Keith Sloan <notifications@github.com> a
écrit :

**Comment by KeithSloan** [comment]
Have tried to update ReadMe with more useful info.

**Comment by lambdam94** [comment]
Thanks Keith
I found the pb: I used the .AppImage (in which python syst is standalone and without lxml lib)with a freecad compilated on my workstation it is ok.the .AppImage is useful for standard user. Do you think that the next AppImage will have the lxml lib?
RegardsDam
-------- Message d'origine --------De : Keith Sloan <notifications@github.com> Date : 02/04/2020  09:55  (GMT+01:00) À : KeithSloan/FreeCAD_Python_GDML <FreeCAD_Python_GDML@noreply.github.com> Cc : lambdam94 <lambdam94@gmail.com>, Author <author@noreply.github.com> Objet : Re: [KeithSloan/FreeCAD_Python_GDML] lxml pb under FreeCAD_0.19-20310 (#35) 

Have tried to update ReadMe with more useful info.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/KeithSloan/FreeCAD_Python_GDML/issues/35#issuecomment-607683610",
"url": "https://github.com/KeithSloan/FreeCAD_Python_GDML/issues/35#issuecomment-607683610",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
