### ISSUE TITLE
Process external XML entities before processing DOM on import

### ISSUE THREAD

**Issue by wdconinc** [KeithSloan/FreeCAD_Python_GDML#4]
Closely related to #3 , but with external entities. This is a separate issue since it is not clear how this should be handled by the importer. It is not merely a question of substituting a value, but should the imported file be included in a single geometry tree, or does FreeCAD provide options to keep the imported file as a separate entity? 

Error message upon import:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/freecad-daily/Mod/GDML/importGDML.py", line 60, in insert
    processGDML(filename)
  File "/usr/lib/freecad-daily/Mod/GDML/importGDML.py", line 217, in processGDML
    tree = ET.parse(filename)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
<class 'xml.etree.ElementTree.ParseError'>: undefined entity &sub2;: line 23, column 3
```

Gist with example gdml code:
https://gist.github.com/wdconinc/64ab0fa85e2f51ff36f813d1831bc7ba

**Comment by wdconinc** [comment]
Reason for this issue is also because it presents a commonly used use case because it allows for modularity and reuse of files structures.

**Comment by wdconinc** [comment]
While using lxml resolves this in principle, it does include all geometry in the same tree in freecad, without splitting up different input GDML files (or their segments) into different files inside the freecad interface. It also breaks the logica links in case one external entity is include multiple times.

**Comment by KeithSloan** [comment]
Not sure how easy this will be to deal with in Python.

Have updated sister development https://github.com/KeithSloan/FreeCAD_Geant4 to include the same workbench in all but name and same export. It uses the Geant4 python library to parse the GDML file so hopefully will handle this and other situations. It does have the disadvantage of needing to install Geant4 from source. It is also VERY slow and you have to click on retry when  FreeCAD prompts about not responding. You need to take care if both FreeCAD extensions are installed as they will both try to say they handle a GDML file and only one will. On my system I have one installed on freecad and the other in freecad-daily

**Comment by KeithSloan** [comment]
Okay, the sister application [https://github.com/KeithSloan/FreeCAD_Geant4](url) uses the Geant libraries to parse the GDML file and now has the same Workbench function. But I still have a problem with entity2.gdml as the Default Volume is not defined.
Tried it with your gdmlviewer and it barfed about Default Volume

> Reading entity2.gdml
- schema validation off
- overlap check off
G4GDML: Reading 'entity2.gdml'...
G4GDML: Reading definitions...
G4GDML: Reading materials...
G4GDML: Reading solids...
G4GDML: Reading 'entity2.gdml' done!
Stripping off GDML names of materials, solids and volumes ...

-------- WWWW ------- G4Exception-START -------- WWWW -------
*** G4Exception : NullSetup
      issued by : G4GDMLReadSetup::getSetup()
Referenced setup 'Default' was not found!Returning NULL pointer!

*** This is just a warning message. ***
-------- WWWW -------- G4Exception-END --------- WWWW -------

Segmentation fault (core dumped)

**Comment by KeithSloan** [comment]
Been thinking further about this problem.

1) I could in effect pre-process the file to create a single file for processing, but then what about if the user then exports the file to GDML, the created file will be just one large created file.

2) I could process the file and any included files into sections, define/materials/solids/structure and then process. I could also add a FreeCAD object that held a filename for each section. Then if somebody
exported a file create the file and sections in the same directory. This would still have a problem if a section had multiple include sections and I am not sure how one could handle this. 

Before I start to try and code would like your thoughts and reaction.

**Comment by KeithSloan** [comment]
Should be fixed in latest workbench branch - so closing.

Please reopen if you find problems.
